# Puerto del microservicio de pacientes
server.port=8082

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/pacientesdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=piedraazul123

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Nombre de la aplicación
spring.application.name=ms-pacientes

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true