services:
  backend:
    build: .
    container_name: piedra-azul-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: valen
      DB_PASSWORD: ""
      DB_NAME: piedra_azul

      AWS_REGION: us-east-1
      AWS_ENDPOINT_URL: http://floci:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_S3_BUCKET: piedra-azul-archivos

  floci:
    image: floci/floci:latest
    container_name: piedra-azul-floci
    ports:
      - "4566:4566"
    environment:
      FLOCI_STORAGE_MODE: hybrid
      FLOCI_STORAGE_PERSISTENT_PATH: /app/data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - floci-data:/app/data

volumes:
  floci-data: