export const TipoEvento = Object.freeze({
  PACIENTE_REGISTRADO: "PACIENTE_REGISTRADO",
  PACIENTE_ACTUALIZADO: "PACIENTE_ACTUALIZADO",

  USUARIO_CREADO: "USUARIO_CREADO",
  LOGIN_EXITOSO: "LOGIN_EXITOSO",
  LOGIN_FALLIDO: "LOGIN_FALLIDO",

  CITA_CREADA: "CITA_CREADA",
  CITA_CANCELADA: "CITA_CANCELADA",
  CITA_CONFIRMADA: "CITA_CONFIRMADA",

  DISPONIBILIDAD_CONFIGURADA: "DISPONIBILIDAD_CONFIGURADA"
});