# Puerto del microservicio de autenticación
server.port=8081

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=piedraazul123

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Nombre de la aplicación
spring.application.name=ms-auth

# ── JWT ─────────────────────────────────────────────
# Debe ser idéntico al del api-gateway
jwt.secret=PiedraAzulSecretKey2026SuperSegura!!
# 86400000 ms = 24 horas
jwt.expiration-ms=86400000